### ISSUE TITLE
EEPROM settings size changes can cause breaks upstream

### ISSUE THREAD

**Issue by Jeff-Ciesielski** [keyme/grbl#55]
We need to make sure that adding a setting to the eeprom doesn't break everything upstream.

Breaks can include:
- Motion breaking due to unknown settings
- Overwriting of null terminators causing garbage in fields
- "EEPROM_ERROR" states due to improperly read settings

**Comment by StephanCoetzee** [comment]
https://github.com/keyme/kiosk/pull/8449 Should fix this.

**Comment by penguinland** [comment]
Closed by https://github.com/keyme/kiosk/pull/8449.
