### ISSUE TITLE
RFC: Turn on C99

### ISSUE THREAD

**Issue by Jeff-Ciesielski** [keyme/grbl#67]
This shouldn't break anything, and will allow us to more tightly scope our variables (and use on-the-spot iterators...)

**Comment by penguinland** [comment]
What all would be required for this change? In principle it sounds like a good idea, but I don't know how that translates to practice.

**Comment by Jeff-Ciesielski** [comment]
It's just a matter of passing -std=c99 to gcc.  I just tried it locally, everything still compiles cleanly.  There are some other things we can take advantage of if we wished (the restrict keyword, inline functions, variadic macros, and flexible array members are all nice things to have access to).

In practice, we're actually taking advantage of a few of these things already (GCC plays fast and loose with its defaults), so the big thing we get is not having to always declare our variables at the top level of a function's scope.

**Comment by StephanCoetzee** [comment]
Why not turn it up to C11 if we are going to change it in any case?

**Comment by mdicicco** [comment]
It goes to 11?

**Comment by Jeff-Ciesielski** [comment]
Only because we couldn't make 10 any more standard.

**Comment by Jeff-Ciesielski** [comment]
I'd also be in favor of turning on C11.  It doesn't really add a ton that's useful to firmware (the biggest things were threading and atomics), but perhaps we could find a use for the new static assertions.
