### ISSUE TITLE
Race condition in probe code (causing WAIT_ROTATE errors in cutter)

### ISSUE THREAD

**Issue by Jeff-Ciesielski** [keyme/grbl#76]
In stepper.c:
```

  // Used to move to carousel magazine
  probe_carousel_monitor();

  // Check if probe is reached, if probing
  if (probe.isprobing)
    probe_check();

```

in probe.c:
```
bool probe_loop()
{
  // Start stepper
  st_prep_buffer();
  st_wake_up();

  SYS_EXEC |= EXEC_CYCLE_START;

  // Stay in this loop until alarm or until
  // the probe is found. probe_check() is called
  // from the stepper ISR to check if the active
  // probe is found.
  while (probe.isprobing) {
    // Check for user reset and allow
    // protocol_execute_runtime to run in this loop 
```

also in probe.c:
```

  if (!probe_loop())
    return;

  uint8_t probe_fail;
  if (sensor == MAG_SENSOR) {
    probe_fail = (probe.carousel_probe_state == PROBE_ACTIVE);
    if (probe_fail)
      memcpy(sys.probe_position, sys.position, sizeof(float) * N_AXIS);
  }
...

  if (sensor == MAG_SENSOR)
    report_probe_parameters(probe_fail);
...
```
It appears what can happen is (due to inertia presumably), we can check the carousel mag sensor (results in false), then very shortly after check the 'probe' sensor (results to true).  The probe sensor returning true causes `probe_loop()` to exit, which in-turn causes `probe_fail` to evaluate to true, causing  a false-positive error to be sent up to motion and then cutter.

**Comment by mdicicco** [comment]
good find!

**Comment by StephanCoetzee** [comment]
I see what you're saying. That can cause probe fails, but not the false mag missing alarms that we've been seeing in the field. Good find. Won't be too difficult to fix.

**Comment by Jeff-Ciesielski** [comment]
We're also seeing probe fails in the field.

**Comment by StephanCoetzee** [comment]
Ok, sure. You can assign this to me and I'll make a PR with a fix. I made a PR regarding this code yesterday (not for the race condition, but for something else in this code). So I think that should be reviewed first.
